### PR TITLE
Drop files and scripts that are integrated in nvidia-video-G06

### PR DESCRIPTION
**Pull request by scaronni**
This goes along with https://github.com/openSUSE/nvidia-driver-G06/pull/31 to remove duplication. Everything that has been moved is in `nvidia-common-G06` now, so the `kmp` packages are requiring it now.

There is still this block:
```
# groups are now dynamic
if [ -f %{_sysconfdir}/modprobe.d/50-nvidia.conf ]; then
  VIDEOGID=`getent group video | cut -d: -f3`
  sed -i "s/33/$VIDEOGID/" %{_sysconfdir}/modprobe.d/50-nvidia.conf
fi
```
Which is not in the `nvidia-driver-G06` package. Either it's not needed or it's needed as well on the closed source module package. What do you think?

### CODE REVIEW

**Comment by scaronni** [comment]
If that block is still needed, and needed by both, it should go into the `nvidia-common-G06` package.

**Comment by sndirsch** [comment]
> This goes along with [openSUSE/nvidia-driver-G06#31](https://github.com/openSUSE/nvidia-driver-G06/pull/31) to remove duplication. Everything that has been moved is in `nvidia-common-G06` now, so the `kmp` packages are requiring it now.
> 
> There is still this block:
> 
> ```
> # groups are now dynamic
> if [ -f %{_sysconfdir}/modprobe.d/50-nvidia.conf ]; then
>   VIDEOGID=`getent group video | cut -d: -f3`
>   sed -i "s/33/$VIDEOGID/" %{_sysconfdir}/modprobe.d/50-nvidia.conf
> fi
> ```
> 
> Which is not in the `nvidia-driver-G06` package. Either it's not needed or it's needed as well on the closed source module package. What do you think?

Yes, we still need it. It's also in `nvidia-driver-G06` package (`kmp-post.sh/kmp-trigger.sh`)

```
# groups are now dynamic
%if 0%{?suse_version} >= 1550
if [ -f /usr/lib/modprobe.d/50-nvidia-default.conf ]; then
%else
if [ -f /etc/modprobe.d/50-nvidia-default.conf ]; then
%endif
  VIDEOGID=`getent group video | cut -d: -f3`
%if 0%{?suse_version} >= 1550
  sed -i "s/33/$VIDEOGID/" /usr/lib/modprobe.d/50-nvidia-default.conf
%else
  sed -i "s/33/$VIDEOGID/" /etc/modprobe.d/50-nvidia-default.conf
%endif
fi
```

**Comment by sndirsch** [comment]
Thanks a lot! Looks good. Let's begin with build-testing.

**Comment by sndirsch** [comment]
Build worked fine. Dependancies look good as well.

**Comment by sndirsch** [comment]
> Yes, we still need it. It's also in `nvidia-driver-G06` package (`kmp-post.sh/kmp-trigger.sh`)
> 
> ```
> # groups are now dynamic
> %if 0%{?suse_version} >= 1550
> if [ -f /usr/lib/modprobe.d/50-nvidia-default.conf ]; then
> %else
> if [ -f /etc/modprobe.d/50-nvidia-default.conf ]; then
> %endif
>   VIDEOGID=`getent group video | cut -d: -f3`
> %if 0%{?suse_version} >= 1550
>   sed -i "s/33/$VIDEOGID/" /usr/lib/modprobe.d/50-nvidia-default.conf
> %else
>   sed -i "s/33/$VIDEOGID/" /etc/modprobe.d/50-nvidia-default.conf
> %endif
> fi
> ```

In our -signed packages I do it differently, so you can even change group ID later. Not sure if we want to introduce that complexity to the modprobe file.

```
install nvidia /sbin/modprobe --ignore-install nvidia NVreg_DeviceFileUID=0 NVreg_DeviceFileGID=$(getent group video | cut -d: -f3) NVreg_DeviceFileMode=0660 NVreg_PreserveVideoMemoryAllocations=1
```

**Comment by scaronni** [comment]
Well if you need that block in both open and close modules let's move it to `nvidia-common-G06`. I'll prepare a MR. Also your signed modules should drop that code and move it to `nvidia-common-G06` as well, so you have just one copy instead of 3.

**Comment by sndirsch** [comment]
> Well if you need that block in both open and close modules let's move it to `nvidia-common-G06`. I'll prepare a MR. 

Thanks a lot!

> Also your signed modules should drop that code and move it to `nvidia-common-G06` as well, so you have just one copy 
> instead of 3.

I would like to, but I don't have access to a subpackage of `nvidia-driver-G06` in the environment where `nvidia-open-driver-G06-signed` is being built (and possibly installed, if neither CUDA nor NVIDA gxf driver repository has been added, e.g. when QA is being done). Most likely I'll add just the same subpackage (with same name) with the same content to `nvidia-open-driver-G06-signed` + dependancies.  I think it's doable to keep 4 sources files (which rarely are chaning) + this block in sync. ;-)

**Comment by scaronni** [comment]
Do you need to have a fully working setup where you sign the module? Because otherwise you can still drop everything and conver the line that says `Requires: nvidia-common-G06 = %{version}` to `Recommends: nvidia-common-G06 = %{version}`. This way it still behaves as the MR intends but can still be installed standalone.

I don't think you need to have all the dracut/modprobe files available to sign the module, right?

**Comment by sndirsch** [comment]
> Do you need to have a fully working setup where you sign the module? Because otherwise you can still drop everything and conver the line that says `Requires: nvidia-common-G06 = %{version}` to `Recommends: nvidia-common-G06 = %{version}`. This way it still behaves as the MR intends but can still be installed standalone.

Yes, but ...

> I don't think you need to have all the dracut/modprobe files available to sign the module, right?

... I don't, but I think it's needed for QA. We could introduce a complete separate package (including sources), which can be part of our distribution. Or we accept, that the world isn't that perfect as we would like to have it. ;-) 

I think it's not such a big deal to have things at two places to sync, which are rarely changing. I mean, for the CUDA repository (`nvidia-driver-G06` and `nvidia-open-driver-G06`) everything is good now. `nvidia-open-driver-G06-signed` is my problem after all.

**Pull request merged**
