### PR TITLE
Drop kernel-firmware-nvidia-gspx-G06 requirement

### PR DESCRIPTION
**Pull request by scaronni**

### CODE REVIEW

**Comment by sndirsch** [comment]
See my comment in https://github.com/openSUSE/nvidia-driver-G06/pull/35

**Comment by sndirsch** [comment]
@scaronni I guess this then can be close as well? Together with https://github.com/openSUSE/nvidia-driver-G06/pull/35

**Comment by scaronni** [comment]
I've replied in the other MR.

**Comment by scaronni** [comment]
Updated the MR as per https://github.com/openSUSE/nvidia-driver-G06/pull/35#issuecomment-2413637838.

**Comment by scaronni** [comment]
Doh! Opening the second one actually reopened also this one :man_facepalming:

**Comment by sndirsch** [comment]
Convinced. Let's go for it. I'll do a small build test soon.

**Comment by sndirsch** [comment]
> Convinced. Let's go for it. I'll do a small build test soon.

Build test worked fine.

**Pull request merged**
