### PR TITLE
Simplify pci_id generation

### PR DESCRIPTION
**Pull request by scaronni**
Hi @sndirsch, here is a simplification for the PCI ID generation. Sorry if I stress on this topic, but as explained in the old merge request I'm trying to use the same logic for both and open.

```
$ ./json-to-pci-id-list.py 
usage: json-to-pci-id-list.py [-h] --flavor FLAVOR (--closed | --open) INPUT_JSON
json-to-pci-id-list.py: error: the following arguments are required: --flavor, INPUT_JSON
```

With this change, internally I can reuse the same logic in `nvidia-driver-G06` to get the full list of closed-only GPUs.

Also:
- This deletes the `pci_ids*` files that are actually not needed to be in the source.
- Adds `python3` as a build requirement.

### CODE REVIEW

**Comment by scaronni** [comment]
Example:

```
$ ./json-to-pci-id-list.py --flavor default --closed supported-gpus-565.57.01.json
Supplements modalias(kernel-default:pci:v000010DEd00000020sv*sd*bc03sc0[02]i00*)
Supplements modalias(kernel-default:pci:v000010DEd00000028sv*sd*bc03sc0[02]i00*)
Supplements modalias(kernel-default:pci:v000010DEd00000029sv*sd*bc03sc0[02]i00*)
[...]
Supplements modalias(kernel-default:pci:v000010DEd000028E0sv*sd*bc03sc0[02]i00*)
Supplements modalias(kernel-default:pci:v000010DEd000028E1sv*sd*bc03sc0[02]i00*)
Supplements modalias(kernel-default:pci:v000010DEd000028F8sv*sd*bc03sc0[02]i00*)
```

**Comment by sndirsch** [comment]
Ok. Waiting for the suggestion for `nvidia-driver-G06`. Or do you want to use this different script only for your internal `nvidia-driver-G06` version?

**Comment by scaronni** [comment]
No, just internally. As we discussed before, you want to keep a list of delta PCI IDs, while we want the full list of IDs for each driver release.

So the merge request is here only on `nvidia-open-driver-G06`. I'll recycle this internally for `nvidia-driver-G06`.

**Comment by scaronni** [comment]
Just fixed some typos.

**Comment by scaronni** [comment]
Thanks!!

**Pull request merged**
