### PR TITLE
updated tarball and pci_ids to version 565.57.01

### PR DESCRIPTION
**Pull request by sndirsch**

### CODE REVIEW

**Comment by sndirsch** [comment]
@scaronni-nvidia JFYI ...

**Comment by sndirsch** [comment]
> @scaronni-nvidia JFYI ...

I would prefer an automatic approach, but

1. the sources are lacking `supported-gpus.json`, but I think it could be added from looking at the `LICENSE` file for it.
2. I'm generating from this information these supplements files, which then are included by the spefile; and this can't be done during building; it needs to be done before ...

The situation can be improved once we have a better idea how to automate this.

**Comment by scaronni** [comment]
> 2. I'm generating from this information these supplements files, which then are included by the spefile; and this can't be done during building; it needs to be done before ...
> 
> The situation can be improved once we have a better idea how to automate this.

I was actually playing with this just before making the merge request for `nvidia-driver-G06`, I was solving it like this:

```
-%include %{S:13}
+%{expand:%(cat %{SOURCE13} | sed -e 's/flavor/default/g') }
```

Maybe instead of generating everything by hand we can add the json file to the repository before building as a minimum step. Btw, you should avoid pushing also the tarball in git..

**Comment by scaronni** [comment]
I will make a proposal in the next days.

**Pull request merged**
